version: "3"
services:

  app:
    image: <IMAGE_NAME>:<IMAGE_VERSION>
    container_name: ${APP_NAME}_app_${APP_INSTANCE}
    restart: unless-stopped
    volumes:
      - ./data/app:<CONTAINER_DATA_PATH>
    ports:
      - 127.0.0.1:8080:<CONTAINER_PORT>
    depends_on:
      - database
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

  database:
    image: <IMAGE_NAME>:<IMAGE_VERSION>
    container_name: ${APP_NAME}_database_${APP_INSTANCE}
    restart: unless-stopped
    volumes:
      - ./data/database:<CONTAINER_DATA_PATH>
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
